// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZoeNBellaLibary2._0.Data;

#nullable disable

namespace ZoeNBellaLibary2._0.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20251215134417_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ZoeNBellaLibary2._0.Models.Book", b =>
                {
                    b.Property<int>("Book_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Book_Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Book_Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Book_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bought_Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFileNmae")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Book_ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Book_ID = 1,
                            Book_Author = "Suzanne Collins",
                            Book_Description = "A novel written by American author Suzanne Collins that follows a cast of characters living in the fictional districts of Panem.",
                            Book_Name = "Hunger Games",
                            Bought_Price = 10,
                            ImageFileNmae = "/images/hungergames.jpg",
                            Rating = 10
                        },
                        new
                        {
                            Book_ID = 2,
                            Book_Author = "Suzanne Collins",
                            Book_Description = "The second book in the Hunger Games trilogy by Suzanne Collins, continuing the story of Katniss Everdeen as she navigates the challenges of the 75th Hunger Games and the brewing rebellion against the Capitol.",
                            Book_Name = "Catching Fire",
                            Bought_Price = 12,
                            ImageFileNmae = "/images/catchingfire.jpg",
                            Rating = 9
                        },
                        new
                        {
                            Book_ID = 3,
                            Book_Author = "Suzanne Collins",
                            Book_Description = "The final installment in Suzanne Collins' Hunger Games trilogy, where Katniss Everdeen becomes the symbol of rebellion against the oppressive Capitol and fights for freedom in Panem.",
                            Book_Name = "Mockingjay",
                            Bought_Price = 15,
                            ImageFileNmae = "/images/mockingjay.jpg",
                            Rating = 8
                        },
                        new
                        {
                            Book_ID = 4,
                            Book_Author = "Joseph Sheridan Le Fanu",
                            Book_Description = "A Gothic horror novella by Joseph Sheridan Le Fanu, featuring a vampire named Carmilla.",
                            Book_Name = "Carmilla",
                            Bought_Price = 8,
                            ImageFileNmae = "/images/carmilla.jpg",
                            Rating = 8
                        },
                        new
                        {
                            Book_ID = 5,
                            Book_Author = "Olivie Blake",
                            Book_Description = "A muder mystery novel by Olivie Blake that follows a real estate agent tasked with selling a creepy mansion.",
                            Book_Name = "Masters of Death",
                            Bought_Price = 12,
                            ImageFileNmae = "/images/mastersofdeath.jpg",
                            Rating = 2
                        },
                        new
                        {
                            Book_ID = 6,
                            Book_Author = "Jennifer Niven",
                            Book_Description = "A novel by Jennifer Niven about a teenage boy who falls in love with a girl who is also dealing with mental health issues.",
                            Book_Name = "All the bright places",
                            Bought_Price = 10,
                            ImageFileNmae = "/images/allthebrightplaces.jpg",
                            Rating = 7
                        },
                        new
                        {
                            Book_ID = 7,
                            Book_Author = "Pat Barker",
                            Book_Description = "A retelling of Homer's Iliad from the perspective of Briseis, a queen who becomes a war prize.",
                            Book_Name = "The Silence of the Girls",
                            Bought_Price = 12,
                            ImageFileNmae = "/images/silenceofthegirls.jpg",
                            Rating = 10
                        },
                        new
                        {
                            Book_ID = 8,
                            Book_Author = "Pat Barker",
                            Book_Description = "The sequel to The Silence of the Girls by Pat Barker, that retells the aftermath of the Trojan War from the perspective of women who survived it.",
                            Book_Name = "The Women of Troy",
                            Bought_Price = 12,
                            ImageFileNmae = "/images/womenof_Troy.jpg",
                            Rating = 10
                        },
                        new
                        {
                            Book_ID = 9,
                            Book_Author = "Uketsu",
                            Book_Description = "A story following a private investigator who is hired to look into a house layout. Which leads to more questions than answers.",
                            Book_Name = "Strange Houses",
                            Bought_Price = 15,
                            ImageFileNmae = "/images/strangehouses.jpg",
                            Rating = 9
                        },
                        new
                        {
                            Book_ID = 10,
                            Book_Author = "Susanne Collins",
                            Book_Description = "The fifth book in the Hunger Games series by Suzanne Collins, set 24 years before the Katniss Everdeen's story. It follows the Hunger Games of Haymitch Abernathy a tribute in the 50th Hunger Games.",
                            Book_Name = "The sunrise on the Reaping",
                            Bought_Price = 15,
                            ImageFileNmae = "/images/sunriseonthereaping.jpg",
                            Rating = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
